site_name: BUFF-EM documentation
site_author: Homer Reid
site_favicon: buffEM.ico

repo_url: https://github.com/homerreid/buff-em/

theme_dir: 'buff-em-mkdocs-theme'

markdown_extensions:
    - wikilinks
    - toc:
        title: Table of Contents
    - attr_list
    - mdx_math:
        enable_dollar_delimiter: True

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']

pages:
- BUFF-EM documentation: 'index.md'
- Examples:
    - 'Power, force, and torque on spheres and Janus particles irradiated by plane waves':  'examples/JanusParticles/index.md'
    - 'Thermal radiation, self-propulsion and self-rotation of a Janus particle': 'examples/JanusParticleNEQ/index.md'
    - 'Thermal self-rotation of a photon torpedo':                          'examples/PhotonTorpedo/index.md'
    - 'Thermal self-rotation of a QED pinwheel':                          'examples/Pinwheel/index.md'
- General reference:
    - 'Top-level overview':                     'reference/TopLevel.md'
    - 'Installation':                           'reference/Installing.md'
    - 'Geometry descriptions':                  'reference/Geometries.md'
    - 'Inhomogeneous/anisotropic materials':    'reference/SVTensors.md'
    - 'Key differences between BUFF and SCUFF': 'reference/BUFFvsSCUFF.md'
- Command-line application reference:
    - 'buff-scatter':                           'applications/buff-scatter.md'
    - 'buff-neq':                               'applications/buff-neq.md'
    - 'buff-analyze':                           'applications/buff-analyze.md'
- API reference:  
    - 'libbuff':                                'API/libbuff.md'
- Technical memo: 
   - 'Technical memo':                          'tex/buff-em-tex.md'
